extends:
  import: classic
  file: pipeline.yaml
agent:
  label: jenkins-go
  container: gcr.io/jenkinsxio-labs-private/jxl
pipelines:
  release:
    pipeline:
      stages:
      - name: release
        agent:
          image: gcr.io/jenkinsxio-labs-private/jxl
        options:
          containerOptions:
            env:
            - name: XDG_CONFIG_HOME
              value: "/builder/home"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        steps:
        - args:
          - apply
          - --prune
          - --all
          - -R
          - -f
          - cluster
          - -f
          - namespaces
          command: kubectl
          dir: /workspace/source
          name: kubectl-apply

  pullRequest:
    pipeline:
      stages:
      - name: pr-checks
        agent:
          image: gcr.io/jenkinsxio-labs-private/jxl
        steps:
        - args:
          - cluster/*
          - namespaces/*
          dir: /workspace/source
          image: garethr/kubeval:latest
          name: kubeval


